export const siteConfig = {
  name: "Shireff Nady",
  title: "Front-End Developer | Web Developer | JavaScript & React Expert",
  description:
    "Shireff Nady - Expert Front-End Developer specializing in React.js, Next.js, TypeScript, and modern web technologies. Building fast, accessible web applications.",
  url: "https://www.shireff.dev",
  ogImage: "https://www.shireff.dev/og-image.jpg",
  locale: "en_US",
  alternateLocale: ["ar_EG"],
  type: "website",
  languages: {
    primary: "en",
    supported: ["en", "ar"],
    hrefLang: [
      { lang: "en", url: "https://www.shireff.dev" },
      { lang: "ar", url: "https://www.shireff.dev" },
      { lang: "x-default", url: "https://www.shireff.dev" },
    ],
  },
  author: {
    name: "Shireff Nady",
    alternateName: ["Shireff", "شريف نادي", "شريف نادى"],
    email: "shireffn369@gmail.com",
    phone: "+201274068946",
    whatsapp: "+201274068946",
    location: "Egypt",
    twitter: "@shireffnady",
    github: "https://github.com/shireff",
    linkedin: "https://www.linkedin.com/in/shireffnady",
  },
  seo: {
    keywords: [
      // Name Variations - English
      "Shireff",
      "Shireff Nady",
      "Shireff N",
      "Shireff Frontend",
      "Shireff Nady Frontend",
      "Shireff Developer",
      "Shireff Nady Developer",
      "Shireff Web Developer",
      "Shireff Nady Web Developer",
      "Shireff React",
      "Shireff Nady React",
      "Shireff Next.js",
      "Shireff Nady Next.js",
      "Shireff Portfolio",
      "Shireff Nady Portfolio",
      
      // Name Variations - Arabic
      "شريف",
      "شريف نادي",
      "شريف نادى",
      "شريف ن",
      "شريف مطور",
      "شريف نادي مطور",
      "شريف نادى مطور",
      "شريف فرونت اند",
      "شريف نادي فرونت اند",
      "شريف نادى فرونت اند",
      "شريف ويب",
      "شريف نادي ويب",
      "شريف نادى ويب",
      "شريف ريأكت",
      "شريف نادي ريأكت",
      "شريف نادى ريأكت",
      
      // Job Titles - English
      "Front-End Developer Egypt",
      "Frontend Developer Egypt",
      "React Developer Egypt",
      "Next.js Developer Egypt",
      "TypeScript Developer",
      "JavaScript Expert",
      "JavaScript Developer Egypt",
      "Web Developer Egypt",
      "UI Developer Egypt",
      "Full Stack Developer Egypt",
      "Software Engineer Egypt",
      "Web Engineer Egypt",
      
      // Job Titles - Arabic
      "مطور فرونت اند",
      "مطور واجهات امامية",
      "مطور ويب",
      "مطور مواقع",
      "مطور ريأكت",
      "مطور جافاسكريبت",
      "مبرمج مواقع",
      "مبرمج ويب",
      "مهندس برمجيات",
      "مطور فرونت اند مصر",
      "مطور ويب مصر",
      
      // Technologies
      "React Developer",
      "React.js Developer",
      "Next.js Developer",
      "Next.js Expert",
      "TypeScript Developer",
      "JavaScript Developer",
      "Node.js Developer",
      "Express.js Developer",
      "Tailwind CSS Developer",
      "Redux Developer",
      "Redux Toolkit",
      
      // Skills & Services
      "Responsive Web Design",
      "Modern Web Development",
      "Web Performance Optimization",
      "SEO Expert",
      "SEO Optimization",
      "Accessibility WCAG",
      "Progressive Web Apps",
      "PWA Developer",
      "React Hooks",
      "Server Side Rendering",
      "SSR Next.js",
      "Static Site Generation",
      "REST API Development",
      "API Integration",
      
      // Location Based
      "Egypt Developer",
      "Egyptian Developer",
      "Cairo Developer",
      "Freelance Developer Egypt",
      "Remote Developer Egypt",
      "مطور مصري",
      "مبرمج مصري",
      "فريلانسر مصر",
      
      // Portfolio & Projects
      "Web Developer Portfolio",
      "Frontend Portfolio",
      "React Portfolio",
      "Developer Portfolio Egypt",
      "معرض اعمال مطور",
      "بورتفوليو مطور",
      
      // Long-tail Keywords
      "Hire React Developer Egypt",
      "Hire Frontend Developer",
      "Freelance React Developer",
      "Freelance Next.js Developer",
      "Professional Web Developer",
      "Experienced Frontend Developer",
      "توظيف مطور ويب",
      "توظيف مطور فرونت اند",
    ],
    structuredData: {
      foundingYear: 2020,
      experienceYears: 5,
      projectsCompleted: 50,
      jobTitle: "Front-End Developer",
      organization: "Freelance / Open Source",
      knowsAbout: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "TypeScript",
        "React.js",
        "Next.js",
        "Redux",
        "Tailwind CSS",
        "Node.js",
        "Express.js",
        "MongoDB",
        "PostgreSQL",
        "SEO Optimization",
        "Web Performance",
        "Responsive Design",
        "Accessibility",
        "Testing",
        "Git",
        "CI/CD",
      ],
      knowsLanguage: [
        {
          name: "English",
          code: "en",
        },
        {
          name: "Arabic",
          code: "ar",
        },
      ],
      serviceTypes: [
        "Web Development",
        "Front-End Development",
        "React Development",
        "Next.js Development",
        "UI/UX Implementation",
        "Web Performance Optimization",
        "SEO Optimization",
        "API Integration",
        "Responsive Design",
      ],
      priceRange: "$$",
      areaServed: "Worldwide",
    },
  },
  links: {
    twitter: "https://twitter.com/shireffnady",
    github: "https://github.com/shireff",
    linkedin: "https://www.linkedin.com/in/shireffnady",
    whatsapp: "https://wa.me/201274068946",
    heroImageUrl: "https://res.cloudinary.com/dhz0pkov6/image/upload/v1768223813/portfolio/photo_5992549228963630140_y_f89mhv.jpg",
    resume:
      "https://drive.google.com/file/d/10BiinrGfzactg5MyC903WwryfY30Igb3/view?usp=sharing",
    // resume: "https://drive.google.com/file/d/1R4OSPHV8ADIz1qNSaSDMQCIs6fZv85T3/view?usp=sharing",
  },
  personalImages: [
    {
      url: "/personal/shireff-1.webp",
      title: "Shireff Nady Full-Stack Developer Professional Portrait",
      alt: "Official professional headshot of Shireff Nady, a Full-Stack Developer and Web Development Expert specializing in React and Next.js",
    },
    {
      url: "/personal/shireff-2.webp",
      title: "Shireff Nady Software Engineer Web Development Portfolio",
      alt: "Shireff Nady software engineer portrait showcasing professional presence for tech consultancy and development",
    },
    {
      url: "/personal/shireff-3.webp",
      title: "Shireff Nady Frontend Expert",
      alt: "Professional photo of Shireff Nady, an experienced Frontend Expert focusing on modern web technologies and UI/UX",
    },
    {
      url: "/personal/shireff-4.webp",
      title: "Shireff Nady React and Next.js Developer Official Photo",
      alt: "Shireff Nady, specialized in React and Next.js development, posing for a professional portfolio image",
    },
    {
      url: "/personal/shireff-5.webp",
      title: "Shireff Nady Modern Web Architecture Specialist Portrait",
      alt: "Portrait of Shireff Nady, a specialist in modern web architecture and full-stack software engineering",
    },
  ],
};

export type SiteConfig = typeof siteConfig;
